export type ExperienceItem={company:string;role:string;startDate:string;endDate:string;location?:string;summary:string;responsibilities?:string[];technologies?:string[];image?:string;companyUrl?:string};
export type Project={name:string;technology:string;href:string;image:string};
export type CardItem={id:string;url:string;title:string};
export const projects:Project[]=[
{name:"ANWAR BALOCH",technology:"REACT",href:"https://tahawebs.github.io/anwarbaloch/",image:"/images/anwar-baloch.webp"},
{name:"KARACHI BRASSERIE",technology:"REACT",href:"https://karachi-brasserie-psi.vercel.app/",image:"/images/karachi-brasserie.webp"},
{name:"HR-MANAGEMENT",technology:".NET",href:"https://github.com/Tahawebs/Attendance-Management",image:"/images/hr-management.webp"}];
export const experiences:ExperienceItem[]=[{company:"Add company name",role:"Add professional role",startDate:"Add start date",endDate:"Add end date",location:"Add location",summary:"Add a concise professional experience summary.",responsibilities:[],technologies:[],image:"/images/experience-1.webp"}];
export const experienceMarqueeCards:CardItem[]=Array.from({length:6},(_,i)=>({id:`experience-${i+1}`,url:`/images/experience-${i+1}.webp`,title:`Professional development experience image ${i+1}`}));
export const portfolio={person:{name:"Muhammad Taha",title:"Full-Stack Developer",specializedTitle:".NET, React & Next.js Developer",experience:"3+ years",location:"Karachi",profileImage:"/images/profile.webp"},contact:{email:"atahaabid35@gmail.com",emailHref:"mailto:atahaabid35@gmail.com",phoneDisplay:"+92 321 8251867",phoneHref:"tel:+923218251867",github:"https://github.com/Tahawebs",linkedin:""},hero:{eyebrow:"FULL-STACK DEVELOPER · 3+ YEARS OF EXPERIENCE",heading:"Building reliable digital products across frontend, backend, and data.",description:"I’m Muhammad Taha, a full-stack developer specializing in .NET, React.js, Next.js, Express.js, and SQL Server. I build responsive web experiences and dependable business applications, from interface implementation and application architecture to database design and deployment."},navigation:["Home","About","Skills","Experience","Projects","Contact"].map(x=>({label:x,href:`#${x.toLowerCase()}`})),skills:{Frontend:["React.js","Next.js","JavaScript","TypeScript","HTML5","CSS3","Tailwind CSS","Bootstrap","Razor Views","Responsive Web Design"],Backend:["C#",".NET",".NET Core",".NET Framework","ASP.NET Core","ASP.NET Core MVC","Express.js","REST API Development"],"Data and Databases":["SQL Server","Entity Framework Core","Dapper","MySQL","Database Design","Query Optimization"],"Development and Delivery":["Git","GitHub","Vercel","Application Deployment","Responsive Development","Requirements Implementation"]},capabilities:[{title:"Backend Development",text:"Maintainable application logic, APIs, business workflows, and services using C#, .NET, ASP.NET Core, and Express.js."},{title:"Frontend Development",text:"Responsive, interactive interfaces with React.js, Next.js, TypeScript, and Tailwind CSS."},{title:"Database Solutions",text:"Database-driven applications using SQL Server, Entity Framework Core, Dapper, and MySQL."},{title:"Full-Stack Delivery",text:"Complete applications across interface, backend, data integration, testing, and deployment."}],experienceOverview:"More than three years delivering web applications, backend systems, internal tooling, and database-driven business solutions. Work has included stakeholder feedback, practical operational workflows, HR attendance functionality, and business intelligence application work.",projects,seo:{title:"Muhammad Taha | Full-Stack .NET, React & Next.js Developer",description:"Muhammad Taha is a full-stack developer with 3+ years of experience building responsive web applications, backend systems, and database-driven software using .NET, React.js, Next.js, Express.js, and SQL Server.",canonical:"https://replace-with-production-domain.example"}} as const;